#How many pearls does it cost to teleport?
cost: 1

#How far can players teleport?
maxdistance: 2000

teleport:
    #Allow players to teleport to other players?
    playertoplayer: true
    #Allow players to teleport to specified coordinates?
    playertocoordinates: true
    #Allow players to teleport to their bed?
    playertobed: true
