name: '${project.name}'
main: com.kdude63.pearltp.Main
version: '${project.version}'
description: Allows players to teleport at the cost of a configurable amount of enderpearls.
author: kdude63
dev-url: '${project.url}'
commands:
    ptp:
       description: Teleports yourself to another player or coordinates.
       usage: "Usage: /ptp <target> or <x> <y> <z>"
       permission: pearltp.teleport
